CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID  int AUTO_INCREMENT,
    EMAIL    varchar,
    LOGIN    varchar,
    NAME     varchar,
    BIRTHDAY date,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    USER_1 int,
    USER_2 int,
    STATUS boolean
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID     int NOT NULL AUTO_INCREMENT,
    MPA_ID   int,
    NAME        varchar,
    DESCRIPTION varchar,
    RELIASEDATE date,
    DURATION    int,
    PRIMARY KEY (FILM_ID)
);

CREATE TABLE IF NOT EXISTS FILMSGENRE
(
    FILM_ID  int,
    GENRE_ID int
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID int NOT NULL AUTO_INCREMENT,
    NAME     varchar,
    PRIMARY KEY (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS LIKES
(
    LIKE_ID int NOT NULL AUTO_INCREMENT,
    FILM_ID int,
    USER_ID int,
    PRIMARY KEY (LIKE_ID)
);

CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID int NOT NULL AUTO_INCREMENT,
    NAME   varchar,
    PRIMARY KEY (MPA_ID)
);

ALTER TABLE FRIENDS
    ADD FOREIGN KEY (USER_1) REFERENCES USERS (USER_ID);

ALTER TABLE FRIENDS
    ADD FOREIGN KEY (USER_2) REFERENCES USERS (USER_ID);

ALTER TABLE LIKES
    ADD FOREIGN KEY  (FILM_ID) REFERENCES FILMS (FILM_ID) ;

ALTER TABLE LIKES
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE FILMS
    ADD FOREIGN KEY (MPA_ID) REFERENCES MPA (MPA_ID);

ALTER TABLE FILMSGENRE
    ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE;

ALTER TABLE FILMSGENRE
    ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID) ;